# Generated by Django 5.1.7 on 2025-05-27 15:06
import django.db.models.deletion
from django.db import migrations, models

def migrate_cart_items( apps, schema_editor ):
    Cart = apps.get_model('main', 'Cart')
    Product = apps.get_model('main', 'Product')
    CartItem = apps.get_model('main', 'CartItem')

    
    for cart in Cart.objects.all():
        
        for product in cart.items.all():
            
            CartItem.objects.create(cart=cart, product=product, quantity=1)  

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_alter_category_parent'),  
    ]

    operations = [
        
        migrations.CreateModel(
        name='CartItem',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('quantity', models.PositiveIntegerField(default=1)),
            ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart')),
            ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
        ],
    ),
        migrations.RunPython(migrate_cart_items),
        
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        
        
       migrations.AddField(
        model_name='cart',
        name='items',
        field=models.ManyToManyField(through='main.CartItem', to='main.Product'),
    ),
]