# Generated by Django 5.1.7 on 2025-05-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cartitem_alter_cart_items'),
        ('main', '0006_auto_20250527_1806'),
    ]

    operations = [
    ]
